name: Secret Debug Test

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret is passed
        run: |
          if [ -z "${{ secrets.TEST }}" ]; then
            echo "Secret is empty or not passed"
          else
            echo "Secret was successfully detected"
          fi
      - name: Hello world action
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          echo "Secret is $TEST"
